### ISSUE TITLE
Out of Memory in AWFY DeltaBlue

### ISSUE THREAD

**Issue by smarr** [oracle/graalpython#215] opened 2021-05-24 21:21 UTC
To reproduce, grab https://github.com/smarr/are-we-fast-yet/tree/932b44ec0a5f004454720a2069413cb9ada76bcb/benchmarks/Python

and run `graalpython harness.py DeltaBlue 1000  12000`

It looks to me as if a list object is retained, because it's the `self` in a `PBuiltinMethod` that is references in a cache.

I am not sure why the structure is so huge in the first place, but it seems the AST probably shouldn't hold on to the list here.

Memory wasn't an issue when I built a Vector on top of `list` and used the essentially same benchmark before.
So, the memory leak only appeared after switching to the builtin list.

Attached a VisualVM screenshot.

<img width="1341" alt="Screen Shot 2021-05-24 at 22 18 54" src="https://user-images.githubusercontent.com/40815/119408923-677dee80-bcde-11eb-8008-7dbb33c92b57.png">

**Comment by msimacek** [comment] 2021-06-28 10:18
Thank you for the report. I cannot reproduce the problem on master branch anymore, I believe it was fixed by 26578d270b9a87d30d1e66ba23797840062ad74f

**Closed by msimacek** 2021-06-28 10:18 UTC
