### ISSUE TITLE
Cannot install Pyyaml

### ISSUE THREAD

**Issue by SZanko** [oracle/graalpython#237] opened 2021-08-30 11:59 UTC
# Softwareplatform

- ArchLinux
- Latest Github release of graalpython

# How to reproduce the bug

```shell
graalpython -m venv venv
source venv/bin/activate
pip install pyyaml
```

# Result

```
Collecting pyyaml
  WARNING: Cache entry deserialization failed, entry ignored
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     |████████████████████████████████| 175 kB 1.0 MB/s
Looking for Graal Python patches for PyYAML
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/stefan/Documents/build/samportable-cli/venv/bin/graalpython /home/stefan/Documents/build/samportable-cli/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmph1jba9tx
         cwd: /tmp/pip-install-33lfywel/pyyaml
    Complete output (11 lines):
    running dist_info
    creating /tmp/pip-modern-metadata-sa7qj5sg/PyYAML.egg-info
    writing /tmp/pip-modern-metadata-sa7qj5sg/PyYAML.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-sa7qj5sg/PyYAML.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-modern-metadata-sa7qj5sg/PyYAML.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-sa7qj5sg/PyYAML.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-modern-metadata-sa7qj5sg/PyYAML.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file '/tmp/pip-modern-metadata-sa7qj5sg/PyYAML.egg-info/SOURCES.txt'
    creating '/tmp/pip-modern-metadata-sa7qj5sg/PyYAML.dist-info'
    error: invalid command 'bdist_wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/stefan/Documents/build/samportable-cli/venv/bin/graalpython /home/szanko/Documents/build/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmph1jba9tx Check the logs for full command output.
```

However no file is created under the location /tmp/tmph1jba9tx

# Expected behaivor

That Pyyaml is installed to the virtualenv

**Comment by msimacek** [comment] 2021-08-30 12:52
Hi @SZanko, thank you for trying graalpython. It seems it's missing the `wheel` package. Can you please try executing `pip install wheel` first (with the virtualenv active) and then try again? I'll try to investigate why CPython doesn't need it in the same situation.

**Comment by SZanko** [comment] 2021-08-30 13:06
@msimacek After following your instructions it worked.
Should I leave the issue open?
Because I think this isn't expected behavior from graalpython.

**Comment by msimacek** [comment] 2021-08-30 13:43
CPython doesn't need `wheel` in this situation even when building from source, so you're right that it's not expected behavior. Hovewer, the problem seems to be already fixed in the latest snapshot, so I will close the issue as fixed. If you want to try the snapshot, you can get the latest one here: https://github.com/graalvm/graalvm-ce-dev-builds/releases/

**Closed by msimacek** 2021-08-30 13:43 UTC
